apiVersion: v1
description: Open source, multi-cloud continuous delivery platform for releasing software changes with high velocity and confidence.
name: spinnaker
version: 2.2.6
appVersion: 1.24.4
home: http://spinnaker.io/
