dependencies:
- name: redis
  version: 10.5.3
  repository: https://charts.helm.sh/stable
  condition: redis.enabled
- name: minio
  version: 5.0.32
  repository: https://charts.helm.sh/stable
  condition: minio.enabled
