version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - TAG="latest"
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
  build:
    commands:
      - echo Change the source directory to ${APP_NAME}
      - cd ${APP_NAME}
      - echo Build a container image
      - docker build --tag "$IMAGE_URI" .
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - sed -i "s@<APPSERVER_V2_IMAGE_URI>@$IMAGE_URI@g" manifests/3-meshed-app-v2.yaml
      - echo Uploading to ${ARTIFACT_BUCKET}
      - aws s3 cp --recursive manifests/ s3://${ARTIFACT_BUCKET}/
artifacts:
  files: 3-meshed-app-v2.yaml
